[repositories]
local = true

[parents]
minecraft = { group = "dev.extframework.core", version = "1.0.6-BETA", use = "local" }
init-hook = { isBuild = true }
resource-loader = { isBuild = true }
keybind = { isBuild = true }
